// js/config.js
window.EMAILJS_CONFIG = {
    PUBLIC_KEY: process.env.EMAILJS_PUBLIC_KEY || 'YOUR_DEFAULT_PUBLIC_KEY',
    SERVICE_ID: process.env.EMAILJS_SERVICE_ID || 'YOUR_DEFAULT_SERVICE_ID',
    SALES_TEMPLATE_ID: process.env.EMAILJS_SALES_TEMPLATE_ID || 'YOUR_DEFAULT_SALES_TEMPLATE_ID',
    THANKYOU_TEMPLATE_ID: process.env.EMAILJS_THANKYOU_TEMPLATE_ID || 'YOUR_DEFAULT_THANKYOU_TEMPLATE_ID'
};